// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzX_f91IZwkJITAHWh_-Ykps_h1o58nl4',
    appId: '1:523986163812:web:3dfd9424c5d523ad7be771',
    messagingSenderId: '523986163812',
    projectId: 'flutter-firebase-a082a',
    authDomain: 'flutter-firebase-a082a.firebaseapp.com',
    storageBucket: 'flutter-firebase-a082a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAySw3jsR_4wgdWS181kNibxc9Yju_yG3Y',
    appId: '1:523986163812:android:d23e8c0b075e0d777be771',
    messagingSenderId: '523986163812',
    projectId: 'flutter-firebase-a082a',
    storageBucket: 'flutter-firebase-a082a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgp2uJkSjBdnFzb0AtoxqPPRi8wR4d68A',
    appId: '1:523986163812:ios:f923c2047e471c0e7be771',
    messagingSenderId: '523986163812',
    projectId: 'flutter-firebase-a082a',
    storageBucket: 'flutter-firebase-a082a.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgp2uJkSjBdnFzb0AtoxqPPRi8wR4d68A',
    appId: '1:523986163812:ios:f923c2047e471c0e7be771',
    messagingSenderId: '523986163812',
    projectId: 'flutter-firebase-a082a',
    storageBucket: 'flutter-firebase-a082a.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzX_f91IZwkJITAHWh_-Ykps_h1o58nl4',
    appId: '1:523986163812:web:71a04c2a0363db537be771',
    messagingSenderId: '523986163812',
    projectId: 'flutter-firebase-a082a',
    authDomain: 'flutter-firebase-a082a.firebaseapp.com',
    storageBucket: 'flutter-firebase-a082a.appspot.com',
  );
}
